OctopusDeploy/OctoVersion

source/OctoVersion.Core/OctoVersionInfo.cs
source/OctoVersion.Tests/WhenStringifyingAnOctoVersionInfo.cs

Discovered in the tentacle army [builds](https://build.octopushq.com/buildConfiguration/TentacleArmy_Build/2130042?buildTab=log&focusLine=710&linesState=496.710&logFilter=undefined)

Nuget doesn't support pre-release suffixes with undescores

---

source/Nuke.OctoVersion/Nuke.OctoVersion.csproj
source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj

As we want to:
* remove the `nuke.octoversion` project from OctoVersion
* build OctoVersion support into nuke itself (as requested/recommended by MatKoch (author of nuke))
* support the same frameworks as nuke does
Should be a fairly noddy change.
If it's 💚, should be good to go.

Add net5.0 target

---

source/OctoVersion.Core/Configuration/AppSettings.cs
source/OctoVersion.Core/ConfigurationBootstrapper.cs
source/OctoVersion.Tests/ConfigurationBootstrapperFixture.cs
source/OctoVersion.Tests/octoversion.json

So that nuke can consume it without bending over backwards with dotnet's weird array arg syntax
dotnet treats command line args as a dictionary - each key must be unique.
This is a bit weird considering most other tools say "pass the arg multiple times" when dealing with an array typed parameter.
Instead of going
```
octoversion --outputformat json
```
you have to go
```
octoversion --outputformat:0 json
```
This PR:
* keeps the existing behavior (to avoid breaking things)
* adds support for sane array parameter parsing from the CLI
* adds tests to ensure that old and new approaches work
Note: the environment variable approach still needs to use existing approach, ie `OCTOVERSION_OutputFormats__0` to pass values.

Support sane cli args for OutputFormat

---

source/OctoVersion.Core/OctoVersionInfo.cs
source/OctoVersion.Tests/WhenStringifyingAnOctoVersionInfo.cs

We were allowing underscores and slashes in these fields, which is not supported according to the spec https://semver.org/spec/v2.0.0.html.
Keen for thoughts around whether this is too much of a breaking change / whether we should be exposing a "semver1" and "semver2" versions in some way.

Make pre release tag and build metadata match semver2 spec

---

source/OctoVersion.Core/OctoVersion.Core.csproj

This allows us to run OctoVersion in GitHub Actions, when we're using Ubuntu 20.0

Update to the latest pre-release of LibGit2Sharp

---

source/Cake.OctoVersion/Logging/CakeOutputFormatter.cs
source/OctoVersion.Core/Configuration/AppSettings.cs
source/OctoVersion.Core/IOutputFormatter.cs
source/OctoVersion.Core/OctoVersionRunner.cs
source/OctoVersion.Core/OutputFormattersProvider.cs
source/OctoVersion.Core/OutputFormatting/Console/ConsoleOutputFormatter.cs
source/OctoVersion.Core/OutputFormatting/Console/QuietConsoleOutputFormatter.cs
source/OctoVersion.Core/OutputFormatting/Environment/EnvironmentOutputFormatter.cs
source/OctoVersion.Core/OutputFormatting/Json/JsonOutputFormatter.cs
source/OctoVersion.Core/OutputFormatting/TeamCity/TeamCityOutputFormatter.cs
source/OctoVersion.Tests/ConfigurationBootstrapperFixture.cs
source/OctoVersion.Tests/OutputFormattersProviderFixture.cs

Relates to https://github.com/nuke-build/nuke/pull/778.
We want to add auto-detection of output formats so that we dont have to hardcode the output format into either nuke or build scripts

Support auto-detection of output formats based on runtime environment

---

source/OctoVersion.Core/VersionNumberCalculation/SimpleVersion.cs
source/OctoVersion.Tests/WhenParsingASimpleVersion.cs

In our workflow we use version tags of the form
`v{major}.{minor}.{patch}`. This change allows OctoVersion to correctly
identify the version at those tagged commits.

Allow `v` Prefix on Tag Versions

---

source/OctoVersion.Core/OctoVersion.Core.csproj

Recently, it seems that LibGit2Sharp has fixed the bit where it's not pulling in the native library properly.
This PR bumps from `0.27.0-preview-0116` to `0.27.0-preview-0158`, to get the fix mentioned in this comment - https://github.com/GitTools/GitVersion/pull/2916#issuecomment-966220582
The below log excerpts are from building our [Caching](https://github.com/octopusdeploy/caching) library.
```
% dotnet tool run nuke
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Microsoft (R) .NET Core SDK version 6.0.101
/Users/anon/dev/Octopus/Caching/build/Build.cs(56,13): warning CS0618: 'Logger.Info(string, params object[])' is obsolete: 'Use Serilog.Log.Information instead' [/Users/anon/dev/Octopus/Caching/build/_build.csproj]
​
███╗   ██╗██╗   ██╗██╗  ██╗███████╗ …
```

Bump LibGit2Sharp

---

.gitignore
source/OctoVersion.Core/Exceptions/ControlledFailureException.cs
source/OctoVersion.Core/Exceptions/RepositoryIsShallowCloneException.cs
source/OctoVersion.Core/Exceptions/RepositoryNotFoundException.cs
source/OctoVersion.Core/VersionNumberCalculation/VersionCalculatorFactory.cs
source/OctoVersion.Tool/Program.cs

If it's a shallow clone, then we cant look through the history to determine the version number
This would've helped resolve this error
Shallow clone shows errors like this:
"Unexpected" errors show like this:

Throw a nice error if it's a shallow clone

---

README.md

for Nuke Octoversion documentation as it doesn't fit the standard usage of Nuke.

Remove reference to OCTOVERSION_CurrentBranch env var

---

.github/CODEOWNERS

[SC-4901] - We decided `team-engineering-productivity-maintainers` was too long, we convinced TSO to change it to `team-engprod`.

Update maintainer team name (again)

---

source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj

Most of this project uses `netstandard2.0`, so it's all happy.
The `global.json` was already targeting `6.0`.
Keeping `netcoreapp3.1` as it's not EOL until the end of the year.
All this PR does is to drop the EOL net5.0 target.

Drop net5.0 target, as it's EOL

---

source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj

So that prettybot can start working again - it was changing to file scoped namespaces, and failing to compile.

Set lang-version to 10

---

source/OctoVersion.Core/OctoVersionRunner.cs
source/OctoVersion.Core/StructuredOutputFactory.cs

We were getting errors:
```
Log event messages should be fragments, not sentences. Avoid a trailing period/full stop.
```
(hah! it contains a trailing full stop!)

Fix resharper warnings about log messages

---

.config/dotnet-tools.json
build.cmd
build.ps1
build.sh
build/Build.cs
build/_build.csproj

Updates nuke to `6.0.3`.
As part of that:
* it removes the dotnet tool `cake.tool` and replaces it with `nuke.globaltool`
* `nuke :update` fixed up a bunch of the build scripts
* tells the nuke `OctoVersion` attribute to use `net6.0`
* updates the `OctoVersion.Tool` version to use one that works on M1 Macs

Update nuke to 6.0.3

---

build/_build.csproj
source/Cake.OctoVersion/Cake.OctoVersion.csproj
source/OctoVersion.Core/OctoVersion.Core.csproj
source/OctoVersion.Tests/ConfigurationBootstrapperFixture.cs
source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tests/SampleData.cs
source/OctoVersion.Tests/SampleDataBuilder.cs
source/OctoVersion.Tests/StructuredOutputFactoryFixture.cs
source/OctoVersion.Tests/WhenParsingASemanticVersion.cs
source/OctoVersion.Tests/WhenParsingASimpleVersion.cs

This PR fixes all remaining code warnings:
* it enables `TreatWarningsAsErrors`, to prevent any backsliding
* it ignores the warning `NU5104` as we need to rely on a pre-release version of gitlib2sharp
* It converts the `SampleData` class to a builder to allow us to be sure about nulls

Fix up all remaining warnings

---

README.md
source/OctoVersion.Core/OctoVersion.Core.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj

So we can use our reserved prefix on nuget.org
Relates to https://github.com/OctopusDeploy/OctopusDeploy/issues/10064

Add Octopus. prefix to nuget pacakges

---

source/Cake.OctoVersion/Cake.OctoVersion.csproj
source/OctoVersion.Core/OctoVersion.Core.csproj
source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj

We're getting [failed builds](https://build.octopushq.com/buildConfiguration/OctopusDeploy_LIbraries_OctoVersion_Ci/5324418?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=5324418_1067_837.1063&logView=flowAware):
>     /opt/buildagent/work/fe69bdc7275df075/source/Cake.OctoVersion/CakeExtensions.cs(11,1): error CS8400: Feature 'file-scoped namespace' is not available in C# 8.0. Please use language version 10.0 or greater. [/opt/buildagent/work/fe69bdc7275df075/source/Cake.OctoVersion/Cake.OctoVersion.csproj]

Update langversion to fix prettybot build

---

source/OctoVersion.Core/OutputFormatting/GitHubActions/GitHubActionsOutputFormatter.cs

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
OctoVersion users will experience pipeline failures after May 31 2023 once GitHub removes these commands - this PR aims to ship a change that uses the new environment file option.
I have used a similar pattern as is already used for the `GITHUB_ENV` handler in the same class.

Change GitHub output formatter to use environment files

---

build.sh
build/Build.cs
build/_build.csproj
global.json
source/OctoVersion.Core/OctoVersion.Core.csproj
source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj
source/OctoVersion.sln

Adds support for net7. 
It also updates nuke to version 7.0.0, and OctoVersion to the `Octopus.OctoVersion.Tool` one instead of the deprecated `OctoVersion.Tool`
I've decided to do it an interesting way, and:
1) build in the standard `mcr.microsoft.com/dotnet/sdk:6.0` container
2) update the `build.sh` to install both dotnet 6 and dotnet 7
3) change the build script to call `./build.sh` directly.
Happy for feedback.
This is a different to @droyad's PR #123, and keeps more of the code in the repo rather than in teamcity.

Upgrade to net7

---

source/OctoVersion.Core/OctoVersionInfo.cs
source/OctoVersion.Core/OutputFormatting/Environment/EnvironmentOutputFormatter.cs
source/OctoVersion.Core/OutputFormatting/GitHubActions/GitHubActionsOutputFormatter.cs
source/OctoVersion.Core/OutputFormatting/TeamCity/TeamCityOutputFormatter.cs
source/OctoVersion.Core/Properties/AssemblyInfo.cs
source/OctoVersion.Tests/EnvironmentOutputFormatterFixture.cs
source/OctoVersion.Tests/OctoVersionInfoFixture.cs
source/OctoVersion.Tests/SampleData.cs
source/OctoVersion.Tests/StructuredOutputFactoryFixture.cs
source/OctoVersion.sln.DotSettings

@corvette63 [reported](https://github.com/OctopusDeploy/OctoVersion/issues/98):
> documentation states output should be formatted such that
> 
> octoversion --CurrentBranch=main --OutputFormats:0=Environment
> 
> ```
> OCTOVERSION_Major=0
> OCTOVERSION_Minor=0
> OCTOVERSION_Patch=5
> OCTOVERSION_MajorMinorPatch=0.0.5
> OCTOVERSION_PreReleaseTag=
> OCTOVERSION_PreReleaseTagWithDash=
> OCTOVERSION_BuildMetadata=
> OCTOVERSION_BuildMetadataWithPlus=
> OCTOVERSION_FullSemVer=0.0.5
> ```
> 
> however actual output is such that
> 
> ```
> OCTOVERSION_PreReleaseTagWithDash: something
> OCTOVERSION_MajorMinorPatch: something
> OCTOVERSION_BuildMetadataWithPlus: something
> OCTOVERSION_FullSemVer: something
> OCTOVERSION_InformationalVersion: something
> OCTOVERSION_NuGetVersion: something
> ``` …

Include missing properties from base class

---

.config/dotnet-tools.json
.nuke/build.schema.json
build.ps1
build.sh
build/Build.cs
build/_build.csproj

Dependabot tried to update nuke to 8.0.0 in https://github.com/OctopusDeploy/OctoVersion/pull/190, which didn't work so well.
This does that upgrade, but also runs `nuke :update`

Update to nuke 8.0.0

---

.github/workflows/ci.yml
.octopus/deployment_process.ocl
source/OctoVersion.Tests/SanitizerFixture.cs

[sc-67608] We are migrating off using Teamcity to run our pipeline builds, due to the work in reducing static secret tokens. Moving to Github Actions will allow us to use the GitHub native token management features which automatically provides short-lived token. 
This PR introduces a new workflow for our project, defined in the `ci.yml` file,  which will run octopus deploy steps  to push the dotnet package into octopus deploy. The steps includes logging into octopus, pushing build information to octopus, pushing a package to octopus and creating a release
- **Package version**: The Nuke step uses the environment variable `env.OCTOVERSION_FullSemVer ` 
- **Push Trigger**: The workflow is triggered on `push` event to the `main` branch. If it is a push request, it will create a release in …

Add CI Octopus Deploy github actions workflow 

---

.github/workflows/ci.yml
.octopus/variables.ocl
octoversion.json

In Octopus, the the main branch is getting released into pre-release. This PR updates the 'main' branch so that it correctly sends it to the production channel

Update to octoversion config to use main

---

.github/workflows/ci.yml

Error with previous action run: 
`Error: At least one step violates the package version rules for the Channel 'Pre-release'. Either correct the package versions for this release, let Octopus select the best channel by omitting the ChannelName argument, select a different channel using the ChannelName argument, or ignore these version rules altogether by using the IgnoreChannelRules argument.`
Channel rules are based off package version rules. This PR removes the channel rules and updates the package version environment branch name based on whether the GitHub action was a scheduled run or not. This way, scheduled runs are sorted into the 'pre-release' environment by default 
In addition, git tags are added for all releases from the main branch (non pre-release)

Update package version branch naming based on schedule trigger & git tags

---

.github/workflows/ci.yml

Update write content permission to enable git tag creation on main

Update github token permissions to create git tag

---

.github/workflows/prettybot-automation.yml

The github PrettyBot workflow creates new PRs, but doesn't close the old ones.
This means if we cant get to them straight away, they stack up.

Close any existing open PRs

---

.github/workflows/ci.yml

So we can run the prettybot builds manually
(we're likely to have to write code to trigger an actions run as github wont run an new action based on something created by an action)

Allow manual trigger of CI build

---

source/Cake.OctoVersion/Cake.OctoVersion.csproj
source/OctoVersion.Core/OctoVersion.Core.csproj
source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj

net6.0 is EOL on November 12, 2024, so we want to remove it
net7.0 is already EOL
[sc-90596]
+semver: breaking

Remove support for net6.0 and net7.0

---

source/OctoVersion.Core/ExtensionMethods/CommitExtensionMethods.cs
source/OctoVersion.Core/ExtensionMethods/StringExtensionMethods.cs
source/OctoVersion.Tests/WhenParsingCommitMessages.cs

In the past, I've been bitten by trying to go `+semver:breaking`, which didn't work, because it expected a space.
This PR makes the parsing a bit more lenient, allowing spaces and different character cases

Be a bit more lenient with parsing semver bumps

---

.github/workflows/ci.yml
build/_build.csproj
global.json
source/OctoVersion.Tests/OctoVersion.Tests.csproj
source/OctoVersion.Tool/OctoVersion.Tool.csproj

OctoVersion is used for Octopus Server, which will soon be upgraded to .NET 9.
When this happens, the octonotes dotnet tool will start running in an environment where the `global.json` specifies .NET 9, so we'll need a .NET 9 compatible tool version.
- Updates `global.json` and the GHA build script to compile with the .NET 9 SDK
- Tests are dual-run against both net8 and net9
- Libraries (dll's) have been left targeting netstandard or net8. The TargetFramework in this context specifies the minimum .NET version required; we need to keep this on net8 so long as it is supported.
- The dotnet tool package now dual-targets net8 and net9. This produces a nuget package with both versions (screenshot below), which will enable the octopus server upgrade

Update build tooling to .net9, tests and tool target both net8 and net9
