OctopusDeploy/OctoVersion

.gitignore, .nuke, .nuke/build.schema.json, .nuke/parameters.json, build.ps1, build.sh, build/Build.cs, build/_build.csproj, global.json
To get access to the new shiny: https://github.com/nuke-build/nuke/blob/master/CHANGELOG.md
=> Upgrade to nuke 5.1.0

source/OctoVersion.Tests/WhenStringifyingAnOctoVersionInfo.cs
The tests were very verbose, and hard to reason about.
=> Refactor tests to be more concise

source/OctoVersion.Core/OctoVersion.Core.csproj
=> Bump to published Octopus.Shellfish version

source/OctoVersion.Core/Configuration/AppSettings.cs, source/OctoVersion.Core/OctoVersionRunner.cs, source/OctoVersion.Tests/OctoVersion.Tests.csproj
We were getting nullable warnings on compile - this fixes them up
=> Fix up nullable warnings

source/OctoVersion.Core/OctoVersionRunner.cs
=> Discards an unused variable

source/OctoVersion.Core/Configuration/AppSettings.cs
=> Fix arg name in xml comments

source/OctoVersion.sln
As we removed cake a long time ago...
=> Remove link to cake file

.github/workflows/dependabot-automerge.yml
[SC-6262]
We are adding a workflow to automatically merge dependabot update PRs if builds are green.
=> Add dependabot automation

README.md
This provides a simpler solution where it is not needed to populate parameters by external build systems which makes it a bit more multi-purpose.
It also expands the example for something that includes the necessary usings and logs a version (shows usage).
Closes #82
=> Updates Nuke documentation for a simpler solution

README.md
As the cake example was pointing to a file that no longer exists
=> Update readme to add cake example

source/Cake.OctoVersion/CakeExtensions.cs, source/Cake.OctoVersion/Logging/CakeOutputFormatter.cs, source/Cake.OctoVersion/Logging/CakeSink.cs
This pull request has been created by OctoVersion > PrettyBot in TeamCity. This is an experiment, please reach out to #team-core-platform-requests in Slack if there are any issues.
=> [PrettyBot] Merge prettybot/refs/heads/main to refs/heads/main

.github/workflows/prettybot-automation.yml
Adds prettybot automerge automation
=> Add prettybot automerge automation

build/Build.cs
This pull request has been created by OctoVersion > PrettyBot in TeamCity. This is an experiment, please reach out to #team-core-platform-requests in Slack if there are any issues.
=> [PrettyBot] Merge prettybot/refs-heads-main to refs/heads/main

build/Build.cs
Reverts OctopusDeploy/OctoVersion#140
PR #140 was created while fixing/testing pretty bot. We would like to keep the changes unmerged so we can perform further testing. Once PrettyBot is fixed it will make these change automatically.
=> Revert "[PrettyBot] Merge prettybot/refs-heads-main to refs/heads/main"

build.sh, global.json, source/OctoVersion.Core/OctoVersion.Core.csproj, source/OctoVersion.Tests/OctoVersion.Tests.csproj, source/OctoVersion.Tool/OctoVersion.Tool.csproj
**How to review this PR:**
What I've done seems reasonable from what I can see, and is pretty much what appears to have been done for .NET 7. I'm mostly seeking a sanity-check that I haven't gone down the wrong track
=> Update to net8

.octopus/deployment_process.ocl, .octopus/deployment_settings.ocl, .octopus/schema_version.ocl, .octopus/variables.ocl
[sc-67608] 
Turning OctoVersion into a CaC deployment in Octopus
=> initial commit of cac deployment process

.github/workflows/prettybot-automation.yml
[sc-67608] 
We are migrating off using Teamcity to run our pipeline builds, due to the work in reducing static secret tokens. Moving to Github Actions will allow us to use the GitHub native token management features which automatically provides short-lived token.
This PR introduces a new workflow for our project, defined in the prettybot-automation.yml file, which it will create a new branch on prettybot/ and run the code cleanup script in a docker container. If there are changes detected in the branch, it will create an automated PR and approval. However, if there are no changes detected, the branch will be deleted.
- Pull Request Approval: The workflow is designed to automatically approve pull requests created by Octobob that start with prettybot/. This automation will speed up the …
=> Add prettybot Github Actions

.github/workflows/prettybot-automation.yml, source/OctoVersion.Tests/StructuredOutputFactoryFixture.cs
This PR fixed the prettybot workflow by adding the following. 
- Updated docker login to v3 
- Allow write access to github repo files to allow writeable permissions to all users (including the github actions runner ) to modify the files when the prettybot script is run  
- Updated git initialisation
=> Update prettybot workflow 

.github/workflows/ci.yml, .github/workflows/prettybot-automation.yml
This PR allows for scheduled runs of CI and Prettybot workflow once a week to help catch any issues related to dependency updates 
[sc-80464]
=> Add github action scheduled workflow 

source/OctoVersion.Tests/SampleData.cs
Boring whitespace for testing.
PrettyBot should come along and remove it.
=> Added whitespace to test code auto-format
